# Generated by Django 4.1.5 on 2023-11-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='phno',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='prev',
            new_name='previous',
        ),
    ]
